- src/Tmds.Ssh/SshConnection.cs
- src/Tmds.Ssh/SshConnectionSettings.cs
- src/Tmds.Ssh/Tmds.Ssh.csproj
> Add SshConnection class

- DESIGN.md
This describes down how data will flow and SSH channels implementation hooks into the `SshConnection`
> Do some design

- src/Tmds.Ssh/KeyExchange.cs
- src/Tmds.Ssh/MessageNumber.cs
- src/Tmds.Ssh/ProtocolVersionExchange.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshClientSettings.cs
- src/Tmds.Ssh/SshConnection.cs
- src/Tmds.Ssh/UserAuthentication.cs
- test/Tmds.Ssh.Tests/ConnectTests.cs
> Split 'connection setup' in 'protocol exchange', 'key exchange' and 'user authentication'

- src/Tmds.Ssh/HMac.cs
- src/Tmds.Ssh/IHMac.cs
- src/Tmds.Ssh/PacketDecoder.cs
- src/Tmds.Ssh/PacketEncoder.cs
- src/Tmds.Ssh/SocketSshConnection.cs
- src/Tmds.Ssh/ThrowHelper.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/40
> Check MAC on receive

- src/Tmds.Ssh/UserAuthentication.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/42
> Handle SSH_MSG_USERAUTH_BANNER

- README.md
- src/Tmds.Ssh/OpenFlags.cs
- src/Tmds.Ssh/SftpClient.PacketType.cs
- src/Tmds.Ssh/SftpClient.PendingOperation.cs
- src/Tmds.Ssh/SftpClient.Reader.cs
- src/Tmds.Ssh/SftpClient.Writer.cs
- src/Tmds.Ssh/SftpClient.cs
- src/Tmds.Ssh/SftpError.cs
- src/Tmds.Ssh/SftpException.cs
- src/Tmds.Ssh/SftpFile.cs
- test/Tmds.Ssh.Tests/RemoteProcessTests.cs
- test/Tmds.Ssh.Tests/SftpClientTests.cs
- Implement Cancellation
- Support concurrent operations
- pool PendingOperation IValueTaskSources
> Sftp improvements

- README.md
- src/Tmds.Ssh/RemoteProcess.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/84.
> RemoteProcess.ReadToEndAsync: remove disposeStreams arg.

- README.md
- src/Tmds.Ssh/DownloadEntriesOptions.cs
- src/Tmds.Ssh/EnumerationOptions.cs
- src/Tmds.Ssh/SftpClient.cs
- src/Tmds.Ssh/SftpFileEntry.cs
- src/Tmds.Ssh/SftpFileSystemEnumerable.cs
- test/Tmds.Ssh.Tests/SftpClientTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/129
Fixes https://github.com/tmds/Tmds.Ssh/issues/128
> Download/Enumerate: support ShouldRecurse/ShouldInclude.

- src/Tmds.Ssh/SftpClient.PendingOperation.cs
- src/Tmds.Ssh/SftpClient.cs
- src/Tmds.Ssh/SshChannel.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshOperationException.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/137.
> Allow larger SFTP packets.

- src/Tmds.Ssh/SftpClient.Writer.cs
- src/Tmds.Ssh/SftpClient.cs
- src/Tmds.Ssh/SftpFile.cs
- src/Tmds.Ssh/SftpFileSystemEnumerable.cs
- src/Tmds.Ssh/SshClient.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/139.
> Make SftpClient methods show up in async stacktraces.

- src/Tmds.Ssh/SftpClient.PendingOperation.cs
- src/Tmds.Ssh/SftpClient.cs
- src/Tmds.Ssh/SftpFileSystemEnumerable.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/136.
> Dispose dir handles on cancellation.

- README.md
- src/Tmds.Ssh/DownloadEntriesOptions.cs
- src/Tmds.Ssh/LocalPath.cs
- src/Tmds.Ssh/RemotePath.cs
- src/Tmds.Ssh/SftpClient.cs
- src/Tmds.Ssh/SftpFileEntry.cs
- src/Tmds.Ssh/ValueStringBuilder.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/142.
> Handle invalid filename chars.

- src/Tmds.Ssh/AsyncNegotiateAuthentication.cs
- src/Tmds.Ssh/UserAuthentication.GssApiAuth.cs
> Make auth cancellable during NegotiateAuthentication.

- Directory.Packages.props
- README.md
- examples/ssh/Program.cs
- examples/ssh/ssh.csproj
- src/Tmds.Ssh/SshClientSettings.SshConfig.cs
- src/Tmds.Ssh/SshConfig.cs
- src/Tmds.Ssh/SshConfigOption.cs
- src/Tmds.Ssh/SshConfigOptionValue.cs
- src/Tmds.Ssh/SshConfigOptions.cs
- src/Tmds.Ssh/SshSession.cs
- src/Tmds.Ssh/Tmds.Ssh.csproj
- test/Tmds.Ssh.Tests/ConnectTests.cs
- test/Tmds.Ssh.Tests/SshConfigTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/219.
@jborean93 fyi
> Support configuring the client in code using ssh_config options.

- README.md
- examples/ssh/Program.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshClientSettings.SshConfig.cs
- src/Tmds.Ssh/SshClientSettings.cs
- src/Tmds.Ssh/SshConfig.cs
- src/Tmds.Ssh/SshConfigOptionValue.cs
- src/Tmds.Ssh/SshConfigSettings.cs
- src/Tmds.Ssh/SshSession.Authentication.cs
- src/Tmds.Ssh/SshSession.KeyExchange.cs
- src/Tmds.Ssh/SshSession.cs
- test/Tmds.Ssh.Tests/ConnectTests.cs
- test/Tmds.Ssh.Tests/SshClientSettingsTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/231.
> SshClientSettings/SshConfigSettings: make List/Dictionary properties mutable.

- README.md
- src/Tmds.Ssh/LocalFileEntry.cs
- src/Tmds.Ssh/SftpChannel.cs
- src/Tmds.Ssh/UploadEntriesOptions.cs
- test/Tmds.Ssh.Tests/SftpClientTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/131.
> Add UploadEntriesOptions.ShouldRecurse.

- README.md
Retrospectively make some notes on how this library does things.
@jborean93 @vcsjones fyi
> Write down some design notes.

- src/Tmds.Ssh/AlgorithmNames.cs
- src/Tmds.Ssh/KeyExchangeContext.cs
- src/Tmds.Ssh/SocketSshConnection.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshConnection.cs
- src/Tmds.Ssh/SshConnectionInfo.cs
- src/Tmds.Ssh/SshSession.KeyExchange.cs
- test/Tmds.Ssh.Tests/ConnectTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/222.
cc @vcsjones
> Implement OpenSSH strict kex extension for mitigating Terrapin attack.

- README.md
- src/Tmds.Ssh/ChaCha20Poly1305PacketDecryptor.cs
- src/Tmds.Ssh/ECDsaPrivateKey.cs
- src/Tmds.Ssh/Ed25519PrivateKey.cs
- src/Tmds.Ssh/PrivateKey.cs
- src/Tmds.Ssh/PrivateKeyCredential.cs
- src/Tmds.Ssh/PrivateKeyParser.OpenSsh.cs
- src/Tmds.Ssh/ROSExtensions.cs
- src/Tmds.Ssh/RsaPrivateKey.cs
- src/Tmds.Ssh/Sequence.cs
- src/Tmds.Ssh/SequenceReader.cs
- src/Tmds.Ssh/SftpChannel.PendingOperation.cs
- src/Tmds.Ssh/SftpChannel.Reader.cs
- src/Tmds.Ssh/SshAgent.cs
- src/Tmds.Ssh/SshAgentCredentials.cs
- src/Tmds.Ssh/SshClientSettings.Defaults.cs
- src/Tmds.Ssh/SshClientSettings.SshConfig.cs
- src/Tmds.Ssh/SshConfig.cs
- src/Tmds.Ssh/SshConfigOption.cs
- src/Tmds.Ssh/SshSession.Authentication.cs
- src/Tmds.Ssh/TransformAndHMacPacketDecryptor.cs
- src/Tmds.Ssh/UserAuthContext.cs
- src/Tmds.Ssh/UserAuthentication.PublicKeyAuth.cs
- src/Tmds.Ssh/UserAuthentication.SshAgentAuth.cs
- test/Tmds.Ssh.Tests/SerializeParseTests.cs
- test/Tmds.Ssh.Tests/SshConfigTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/213.
cc @jborean93
> Support auth using SSH Agent keys.

- README.md
- src/Tmds.Ssh/SshClientLogger.cs
- src/Tmds.Ssh/SshClientSettings.Defaults.cs
- src/Tmds.Ssh/SshClientSettings.SshConfig.cs
- src/Tmds.Ssh/UserAuthentication.PublicKeyAuth.cs
- src/Tmds.Ssh/UserAuthentication.SshAgentAuth.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/284.
> SSH Agent: avoid interactive prompts for keys that don't match server.

- README.md
- src/Tmds.Ssh/SshAgent.cs
- src/Tmds.Ssh/SshAgentCredentials.cs
- src/Tmds.Ssh/SshClientLogger.cs
- src/Tmds.Ssh/UserAuthentication.SshAgentAuth.cs
- test/Tmds.Ssh.Tests/SshAgentCredentialsTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/289.
> SshAgentCredentials: add test.

- src/Tmds.Ssh/PrivateKeyParser.OpenSsh.cs
- src/Tmds.Ssh/PrivateKeyParser.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/282.
> Review key load exceptions.

- README.md
- src/Tmds.Ssh/AlgorithmNames.cs
- src/Tmds.Ssh/Curve25519KeyExchange.cs
- src/Tmds.Ssh/KeyExchangeAlgorithmFactory.cs
- src/Tmds.Ssh/SNtruPrime761X25519Sha512KeyExchange.cs
- src/Tmds.Ssh/SshClientSettings.Defaults.cs
- test/Tmds.Ssh.Tests/SshClientSettingsTests.cs
- test/Tmds.Ssh.Tests/sshd_container/Dockerfile
Contributes to https://github.com/tmds/Tmds.Ssh/issues/302
> Add support for sntrup761x25519-sha512 key exchange method

- src/Tmds.Ssh/ArgumentValidation.cs
- src/Tmds.Ssh/ConnectEndPoint.cs
- src/Tmds.Ssh/RemoteEndPoint.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshClientSettings.cs
- test/Tmds.Ssh.Tests/ConnectTests.cs
- test/Tmds.Ssh.Tests/ProxyTests.cs
- test/Tmds.Ssh.Tests/SshClientSettingsTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/317
> Accept ssh uris as destination string.

- src/Tmds.Ssh/AlgorithmNames.cs
- src/Tmds.Ssh/Curve25519KeyExchange.cs
- src/Tmds.Ssh/ECDHKeyExchange.cs
- src/Tmds.Ssh/ECDsaPrivateKey.cs
- src/Tmds.Ssh/ECDsaPublicKey.cs
- src/Tmds.Ssh/Ed25519PublicKey.cs
- src/Tmds.Ssh/HostKey.cs
- src/Tmds.Ssh/KeyExchange.cs
- src/Tmds.Ssh/MLKem768X25519KeyExchange.cs
- src/Tmds.Ssh/PrivateKeyCredential.cs
- src/Tmds.Ssh/PublicKey.cs
- src/Tmds.Ssh/RsaPublicKey.cs
- src/Tmds.Ssh/SNtruPrime761X25519KeyExchange.cs
- src/Tmds.Ssh/SshAgentPrivateKey.cs
- src/Tmds.Ssh/TrustedHostKeys.cs
This does an early check than the existing check which happens at the signature verification.
> Check allowed host key algorithms before host verification.

- src/Tmds.Ssh/AlgorithmNames.cs
- src/Tmds.Ssh/ECDsaPrivateKey.cs
- src/Tmds.Ssh/ECDsaPublicKey.cs
- src/Tmds.Ssh/Ed25519PublicKey.cs
- src/Tmds.Ssh/HostKey.ParseCertificate.cs
- src/Tmds.Ssh/HostKey.cs
- src/Tmds.Ssh/HostKeyAuthentication.cs
- src/Tmds.Ssh/HostKeyVerification.cs
- src/Tmds.Ssh/KeyExchange.cs
- src/Tmds.Ssh/KnownHostsFile.cs
- src/Tmds.Ssh/RsaPrivateKey.cs
- src/Tmds.Ssh/RsaPublicKey.cs
- src/Tmds.Ssh/SshKey.cs
- src/Tmds.Ssh/TrustedHostKeys.cs
- test/Tmds.Ssh.Tests/ConnectTests.cs
- test/Tmds.Ssh.Tests/HostKeyAlgorithmTests.cs
- test/Tmds.Ssh.Tests/KnownHostsTests.cs
- test/Tmds.Ssh.Tests/SshServer.cs
When the host key is a certificate, besides checking the certificate, and the certificate authority, also check the signed key against the known hosts.
> Check signed key against known hosts.

- README.md
- src/Tmds.Ssh/AlgorithmNames.cs
- src/Tmds.Ssh/ArgumentValidation.cs
- src/Tmds.Ssh/Constants.cs
- src/Tmds.Ssh/KnownNameStrings.cs
- src/Tmds.Ssh/RemoteConnection.cs
- src/Tmds.Ssh/RemoteEndPoint.cs
- src/Tmds.Ssh/RemoteListener.cs
- src/Tmds.Ssh/SshChannel.OpenMessages.cs
- src/Tmds.Ssh/SshChannel.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshSequencePoolExtensions.cs
- src/Tmds.Ssh/SshSession.cs
- test/Tmds.Ssh.Tests/ChannelDataStreamTests.cs
- test/Tmds.Ssh.Tests/PublicApiTest.PublicApi.DotNet.verified.txt
Fixes https://github.com/tmds/Tmds.Ssh/issues/255.
> Support TCP/IP remote forward.

- src/Tmds.Ssh/SshSession.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/366.
> Ignore SSH_MSG_IGNORE.

- test/Tmds.Ssh.Tests/SshAgentCredentialsTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/308.
> SshAgentCredentialsTests: give the ssh-agent some time to start before adding keys.

- examples/ssh/Program.cs
- examples/ssh/UnixStandardInputReader.cs
- examples/ssh/WindowsInterop.cs
- examples/ssh/WindowsStandardInputReader.cs
- examples/ssh/WindowsTerminalConfig.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/379.
> ssh example: support terminal allocation on Windows.
