tmds/Tmds.Ssh

- README.md
- src/Tmds.Ssh/ISshClientImplementation.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshSession.cs
- test/Tmds.Ssh.Tests/RemoteProcessTests.cs
- test/Tmds.Ssh.Tests/SshServer.cs
- test/Tmds.Ssh.Tests/sshd_container/Dockerfile
Adds the ExecuteSubsystemAsync call which can create an SSH channel from a subsystem and return the RemoteProcess interface. This is used when the SSH server defines custom subsystems in its sshd_config file that allows a client to create a channel using a pre-defined subsystem name rather than through an explicit command line argument.
Fixes: https://github.com/tmds/Tmds.Ssh/issues/182
> Add ExecuteSubsystemAsync for subsystem based proc

- src/Tmds.Ssh/SftpChannel.cs
Correct order of parameters in call to replaceInvalidCharacters in SftpChannel.
Fixes #185
> Correct order of parameters in call to replaceInvalidCharacters in SftpChannel.

- src/Tmds.Ssh/SshClientSettings.cs
- test/Tmds.Ssh.Tests/SshClientSettingsTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/189.
@jborean93 ptal.
> SshClientSettings: support parsing usernames that include a realm.

- README.md
- src/Tmds.Ssh/SshClientSettings.cs
> DefaultCredentials: add KerberosCredential.

- README.md
- src/Tmds.Ssh/AlgorithmNames.cs
- src/Tmds.Ssh/ChaCha20Poly1305PacketDecoder.cs
- src/Tmds.Ssh/ChaCha20Poly1305PacketEncDecBase.cs
- src/Tmds.Ssh/ChaCha20Poly1305PacketEncoder.cs
- src/Tmds.Ssh/ECDHKeyExchange.cs
- src/Tmds.Ssh/EncryptionAlgorithm.cs
- src/Tmds.Ssh/SshChannel.cs
- src/Tmds.Ssh/SshClientSettings.Defaults.cs
- test/Tmds.Ssh.Tests/CipherTests.cs
- test/Tmds.Ssh.Tests/RemoteProcessTests.cs
- test/Tmds.Ssh.Tests/SshClientSettingsTests.cs
- test/Tmds.Ssh.Tests/Tmds.Ssh.Tests.csproj
- test/Tmds.Ssh.Tests/xunit.runner.json
Fixes https://github.com/tmds/Tmds.Ssh/issues/214.
@jborean93 fyi
> Support chacha20-poly1305@openssh.com.

- src/Tmds.Ssh/PrivateKeyCredential.cs
- src/Tmds.Ssh/SshClientLogger.cs
- src/Tmds.Ssh/UserAuthentication.PublicKeyAuth.cs
This enables the key store use-case described in https://github.com/tmds/Tmds.Ssh/issues/205#issuecomment-2295601168.
This adds support for implementing such keys by deriving from `PrivateKeyCredential`.
We re-use the BCL `RSA` and `ECDsa` classes as abstractions for the key operations.
The implementation can be enhanced latter on by introducing our own abstractions for the key types. This would enable async key operations, and supporting key types the BCL has no abstraction for (like ED25519).
@jborean93 ptal.
> Support using private keys that are not stored in files.

- README.md
- src/Tmds.Ssh/PrivateKeyCredential.cs
- src/Tmds.Ssh/PrivateKeyParser.OpenSsh.cs
- src/Tmds.Ssh/PrivateKeyParser.RsaPkcs1.cs
- src/Tmds.Ssh/PrivateKeyParser.cs
- test/Tmds.Ssh.Tests/PrivateKeyCredentialTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/205.
@jborean93 ptal.
> PrivateKeyCredential: support loading key from char array.

- README.md
- src/Tmds.Ssh/AesCtr.cs
- src/Tmds.Ssh/OpenSshKeyCipher.cs
- src/Tmds.Ssh/PacketEncryptionAlgorithm.cs
- test/Tmds.Ssh.Tests/PrivateKeyCredentialTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/210.
cc @jborean93
> Support decoding private keys that use the chacha20-poly1305@openssh.com cipher.

- Directory.Packages.props
- README.md
- examples/azure_key/AzureECDsaKey.cs
- examples/azure_key/AzureKeyCredential.cs
- examples/azure_key/AzureRsaKey.cs
- examples/azure_key/Program.cs
- examples/azure_key/README.md
- examples/azure_key/azure_key.csproj
- src/Tmds.Ssh/PrivateKeyCredential.cs
- test/Tmds.Ssh.Tests/PrivateKeyCredentialTests.cs
Adds an example of using this library with a private key hosted in Azure Key Vault. This also includes a fix for loading an ephemeral ECDSA key from the .NET object by properly checking the curve OID value.
> Add Azure Key example and fix ECDSA OID check

- src/Tmds.Ssh/SftpChannel.PendingOperation.cs
- src/Tmds.Ssh/SftpChannel.cs
- src/Tmds.Ssh/SftpClient.cs
- src/Tmds.Ssh/SftpFileSystemEnumerable.cs
- test/Tmds.Ssh.Tests/SftpClientTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/245.
> SftpFileSystemEnumerator: don't throw when nested directory is no longer found during recursion

- README.md
- src/Tmds.Ssh/ISshChannel.cs
- src/Tmds.Ssh/LocalForward.cs
- src/Tmds.Ssh/SshChannel.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshDataStream.cs
- src/Tmds.Ssh/SshLoggers.cs
- src/Tmds.Ssh/SshPortForwardLogger.cs
- src/Tmds.Ssh/SshSequencePoolExtensions.cs
- src/Tmds.Ssh/SshSession.cs
- test/Tmds.Ssh.Tests/LocalForwardTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/256.
> Add LocalForward API.

- src/Tmds.Ssh/SftpChannel.cs
- src/Tmds.Ssh/SftpClient.cs
- test/Tmds.Ssh.Tests/SftpClientTests.cs
> Support downloading to a Stream (#261)

- README.md
- src/Tmds.Ssh/SftpChannel.cs
- src/Tmds.Ssh/SftpClient.cs
- test/Tmds.Ssh.Tests/SftpClientTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/267.
cc @yokrysty
> SftpClient: support uploading file from Stream.

- src/Tmds.Ssh/BigIntegerExtensions.cs
- src/Tmds.Ssh/PrivateKeyParser.OpenSsh.cs
We were not meeting some length expectations for parameters provided to the .NET RSA class.
Fixes https://github.com/tmds/Tmds.Ssh/pull/272#issuecomment-2539716021.
cc @yokrysty @jborean93
> PrivateKeyCredential: fix issue when loading some RSA keys.

- README.md
- src/Tmds.Ssh/AlgorithmNames.cs
- src/Tmds.Ssh/ECDsaPrivateKey.cs
- src/Tmds.Ssh/Ed25519PrivateKey.cs
- src/Tmds.Ssh/PrivateKey.cs
- src/Tmds.Ssh/PrivateKeyCredential.cs
- src/Tmds.Ssh/PrivateKeyParser.OpenSsh.cs
- src/Tmds.Ssh/PrivateKeyParser.cs
- src/Tmds.Ssh/RsaPrivateKey.cs
- src/Tmds.Ssh/SshAgentPrivateKey.cs
- src/Tmds.Ssh/SshClientLogger.cs
- src/Tmds.Ssh/UserAuthentication.PublicKeyAuth.cs
- test/Tmds.Ssh.Tests/PrivateKeyCredentialTests.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/285.
> PrivateKeyCredential: support avoiding prompts for keys that server won't accept.

- README.md
- src/Tmds.Ssh/AlgorithmNames.cs
- src/Tmds.Ssh/BigIntegerExtensions.cs
- src/Tmds.Ssh/Curve25519KeyExchange.cs
- src/Tmds.Ssh/ECDHKeyExchange.cs
- src/Tmds.Ssh/KeyExchange.cs
- src/Tmds.Ssh/KeyExchangeAlgorithmFactory.cs
- src/Tmds.Ssh/SshClientSettings.Defaults.cs
- test/Tmds.Ssh.Tests/KeyExchangeAlgorithmTests.cs
- test/Tmds.Ssh.Tests/SshClientSettingsTests.cs
This PR adds support for `curve25519-sha2` key exchange method described by https://datatracker.ietf.org/doc/html/rfc8731
Close https://github.com/tmds/Tmds.Ssh/issues/307
> Add support for curve25519-sha256 key exchange method

- src/Tmds.Ssh/SshAgent.cs
Adds logic to use the SSH_AUTH_SOCK environment variable when selecting the SSH Agent named pipe on Windows. If the env var is unset then the default openssh-ssh-agent is used instead.
It turns out that `ssh.exe` or other tools like `ssh-add.exe` on Windows will use the value of `SSH_AUTH_SOCK` env var so this change replicates that behaviour. It also adds some extra checks on the value to ensure it is in the form or `\\.\pipe\...`.
> Add env var check for Windows ssh-agent pipe name

- Directory.Packages.props
- test/Tmds.Ssh.Tests/PublicApiTest.PublicApi.DotNet.verified.txt
- test/Tmds.Ssh.Tests/PublicApiTests.cs
- test/Tmds.Ssh.Tests/Tmds.Ssh.Tests.csproj
Based on https://andrewlock.net/preventing-breaking-changes-in-public-apis-with-publicapigenerator/.
> Add test to track public API changes.

- src/Tmds.Ssh/ECDsaPrivateKey.cs
- src/Tmds.Ssh/ECDsaPublicKey.cs
- src/Tmds.Ssh/Ed25519PrivateKey.cs
- src/Tmds.Ssh/Ed25519PublicKey.cs
- src/Tmds.Ssh/HostKey.ParseCertificate.cs
- src/Tmds.Ssh/Name.cs
- src/Tmds.Ssh/PublicKeyAlgorithm.cs
- src/Tmds.Ssh/RsaPrivateKey.cs
- src/Tmds.Ssh/RsaPublicKey.cs
- src/Tmds.Ssh/SequenceReader.cs
- src/Tmds.Ssh/SshAgent.cs
- src/Tmds.Ssh/SshAgentPrivateKey.cs
- src/Tmds.Ssh/StreamSshConnection.cs
- src/Tmds.Ssh/ThrowHelper.cs
- src/Tmds.Ssh/UserAuthContext.cs
- src/Tmds.Ssh/UserAuthentication.GssApiAuth.cs
- src/Tmds.Ssh/UserAuthentication.PublicKeyAuth.cs
This is code that may be used outside the SSH protocol for reading data. It doesn't make sense to throw ProtocolException (which inherits SshConnectionException) for those use-cases.
> Don't throw ProtocolException for invalid data.

- README.md
- src/Tmds.Ssh/LocalForward.cs
- src/Tmds.Ssh/SshClient.cs
- src/Tmds.Ssh/SshLoggers.cs
- test/Tmds.Ssh.Tests/LocalForwardTests.cs
- test/Tmds.Ssh.Tests/PublicApiTest.PublicApi.DotNet.verified.txt
This is for consistency with 'RemoteForward'.
> [breaking] Rename DirectForward to LocalForward.

- src/Tmds.Ssh/LocalForward.cs
- src/Tmds.Ssh/RemoteForward.cs
- src/Tmds.Ssh/SocksForward.cs
- test/Tmds.Ssh.Tests/LocalForwardTests.cs
- test/Tmds.Ssh.Tests/PublicApiTest.PublicApi.DotNet.verified.txt
- test/Tmds.Ssh.Tests/RemoteForwardTests.cs
This is for consistency with 'RemoteListener'.
> [breaking] {Local,Remote,Socks}Forward: rename EndPoint property to ListenEndPoint

- src/Tmds.Ssh/SftpChannel.Reader.cs
- src/Tmds.Ssh/SftpChannel.cs
Fixes https://github.com/tmds/Tmds.Ssh/issues/356#issuecomment-2669147591.
> SftpClient: allow SSH_FXP_VERSION extension data to be non-UTF8.

- Directory.Packages.props
- src/Tmds.Ssh/MLKem768X25519KeyExchange.cs
- src/Tmds.Ssh/Tmds.Ssh.csproj
.NET 10 adds ML-Kem to BCL. For lower targets, it adds support from [Microsoft.Bcl.Cryptography](https://www.nuget.org/packages/Microsoft.Bcl.Cryptography/) nuget package.
See https://github.com/dotnet/runtime/issues/113508
> Use BCL MLKem

- README.md
- src/Tmds.Ssh/DownloadEntriesOptions.cs
- src/Tmds.Ssh/SftpChannel.cs
- src/Tmds.Ssh/UploadEntriesOptions.cs
- test/Tmds.Ssh.Tests/PublicApiTest.PublicApi.DotNet.verified.txt
- test/Tmds.Ssh.Tests/SftpClientTests.cs
It doesn't make sense to create empty directories when RecurseSubdirectories is set to false. This renames it to IncludeSubdirectories and when set to false, it doesn't create empty directories.
> {Download/Upload}EntriesOptions: change RecurseSubdirectories to IncludeSubdirectories.
